### ISSUE TITLE
Androids boots without Magisk

### ISSUE THREAD

**Issue by sanderDijkxhoorn** [abing7k/redroid-script#9]
I am using the following docker-compose.yml

```
services:
  redroid1:
    privileged: true
    volumes:
      - ./data1:/data
    ports:
      - 5555:5555
    command:
      - androidboot.redroid_gpu_mode=auto
      - ro.product.cpu.abilist0=x86_64,arm64-v8a,x86,armeabi-v7a,armeabi
      - ro.product.cpu.abilist64=x86_64,arm64-v8a
      - ro.product.cpu.abilist32=x86,armeabi-v7a,armeabi
      - ro.dalvik.vm.isa.arm=x86
      - ro.dalvik.vm.isa.arm64=x86_64
      - ro.enable.native.bridge.exec=1
      - ro.dalvik.vm.native.bridge=libndk_translation.so
      - ro.ndk_translation.version=0.2.2
    container_name: redroid1
    image: 'abing7k/redroid:a11_magisk_ndk_amd'
    restart: always
```
 
 I did notice some magic related logs with read-only errors:

```
[Sat Jun  1 09:52:23 2024] init: starting service 'exec 23 (/sbin/magisk --auto-selinux --boot-complete)'...
[Sat Jun  1 09:52:23 2024] init: createProcessGroup(0, 1197) failed for service 'exec 23 (/sbin/magisk --auto-selinux --boot-complete)': Read-only file system
[Sat Jun  1 09:52:23 2024] init: SVC_EXEC service 'exec 23 (/sbin/magisk --auto-selinux --boot-complete)' pid 1197 (uid 0 gid 0+0 context u:r:su:s0) started; waiting...
[Sat Jun  1 09:52:23 2024] init: Service 'exec 23 (/sbin/magisk --auto-selinux --boot-complete)' (pid 1197) exited with status 0 waiting took 0.001000 seconds
[Sat Jun  1 09:52:23 2024] init: Sending signal 9 to service 'exec 23 (/sbin/magisk --auto-selinux --boot-complete)' (pid 1197) process group...
[Sat Jun  1 09:52:23 2024] init: starting service 'exec 24 (/system/bin/sh -c if [ ! -e /data/data/io.github.huskydg.magisk ] ; then pm install /system/etc/init/magisk/magisk.apk ; fi)'...
[Sat Jun  1 09:52:23 2024] init: createProcessGroup(0, 1210) failed for service 'exec 24 (/system/bin/sh -c if [ ! -e /data/data/io.github.huskydg.magisk ] ; then pm install /system/etc/init/magisk/magisk.apk ; fi)': Read-only file system
[Sat Jun  1 09:52:23 2024] init: SVC_EXEC service 'exec 24 (/system/bin/sh -c if [ ! -e /data/data/io.github.huskydg.magisk ] ; then pm install /system/etc/init/magisk/magisk.apk ; fi)' pid 1210 (uid 0 gid 0+0 context default) started; waiting...
[Sat Jun  1 09:52:23 2024] init: Service 'exec 24 (/system/bin/sh -c if [ ! -e /data/data/io.github.huskydg.magisk ] ; then pm install /system/etc/init/magisk/magisk.apk ; fi)' (pid 1210) exited with status 1 waiting took 0.029000 seconds
[Sat Jun  1 09:52:23 2024] init: Sending signal 9 to service 'exec 24 (/system/bin/sh -c if [ ! -e /data/data/io.github.huskydg.magisk ] ; then pm install /system/etc/init/magisk/magisk.apk ; fi)' (pid 1210) process group...
[Sat Jun  1 09:52:23 2024] init: processing action (sys.boot_completed=1 && sys.bootstat.first_boot_completed=0) from (/system/etc/init/bootstat.rc:77)
[Sat Jun  1 09:52:23 2024] init: starting service 'exec 25 (/system/bin/bootstat --record_boot_complete --record_boot_reason --record_time_since_factory_reset -l)'...
```
